package com.letstrack.app.data.repository

import com.letstrack.app.data.local.dao.BankAccountDao
import com.letstrack.app.data.local.entity.BankAccountEntity
import com.letstrack.app.domain.model.BankAccount
import com.letstrack.app.domain.repository.BankAccountRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import org.json.JSONArray
import javax.inject.Inject

class BankAccountRepositoryImpl @Inject constructor(
    private val bankAccountDao: BankAccountDao
) : BankAccountRepository {

    override fun getAllActiveAccounts(): Flow<List<BankAccount>> {
        return bankAccountDao.getAllActiveAccounts().map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    override suspend fun getAccountById(id: Long): BankAccount? {
        return bankAccountDao.getAccountById(id)?.toDomainModel()
    }

    override suspend fun getAccountByNumber(accountNumber: String): BankAccount? {
        return bankAccountDao.getAccountByNumber(accountNumber)?.toDomainModel()
    }

    override suspend fun getActiveAccountsList(): List<BankAccount> {
        return bankAccountDao.getActiveAccountsList().map { it.toDomainModel() }
    }

    override suspend fun insertAccount(account: BankAccount): Long {
        return bankAccountDao.insertAccount(account.toEntity())
    }

    override suspend fun updateAccount(account: BankAccount) {
        bankAccountDao.updateAccount(account.toEntity())
    }

    override suspend fun deactivateAccount(id: Long) {
        bankAccountDao.deactivateAccount(id)
    }

    override suspend fun updateAccountUsage(id: Long, timestamp: Long, smsDate: Long) {
        bankAccountDao.updateAccountUsage(id, timestamp, smsDate)
    }

    override suspend fun deleteAccount(id: Long) {
        bankAccountDao.deleteAccount(id)
    }

    override suspend fun getActiveAccountCount(): Int {
        return bankAccountDao.getActiveAccountCount()
    }

    private fun BankAccountEntity.toDomainModel() = BankAccount(
        id = id,
        accountNumber = accountNumber,
        bankName = bankName,
        accountNickname = accountNickname,
        senderPatterns = jsonToList(senderPatterns),
        sampleDebitSms = sampleDebitSms,
        sampleCreditSms = sampleCreditSms,
        debitKeywords = jsonToList(debitKeywords),
        creditKeywords = jsonToList(creditKeywords),
        isActive = isActive,
        createdAt = createdAt,
        smsProcessedCount = smsProcessedCount,
        lastSmsDate = lastSmsDate
    )

    private fun BankAccount.toEntity() = BankAccountEntity(
        id = id,
        accountNumber = accountNumber,
        bankName = bankName,
        accountNickname = accountNickname,
        senderPatterns = listToJson(senderPatterns),
        sampleDebitSms = sampleDebitSms,
        sampleCreditSms = sampleCreditSms,
        debitKeywords = listToJson(debitKeywords),
        creditKeywords = listToJson(creditKeywords),
        amountPattern = "", // Will be generated by SMS parser
        datePattern = "",
        balancePattern = "",
        accountPattern = "",
        merchantPattern = "",
        isActive = isActive,
        createdAt = createdAt,
        smsProcessedCount = smsProcessedCount,
        lastSmsDate = lastSmsDate
    )

    private fun listToJson(list: List<String>): String {
        val jsonArray = JSONArray()
        list.forEach { jsonArray.put(it) }
        return jsonArray.toString()
    }

    private fun jsonToList(json: String): List<String> {
        val list = mutableListOf<String>()
        try {
            val jsonArray = JSONArray(json)
            for (i in 0 until jsonArray.length()) {
                list.add(jsonArray.getString(i))
            }
        } catch (e: Exception) {
            // Return empty list if JSON parsing fails
        }
        return list
    }
}
