package com.letstrack.app.data.repository

import com.letstrack.app.data.local.dao.BudgetDao
import com.letstrack.app.data.local.entity.BudgetEntity
import com.letstrack.app.domain.model.Budget
import com.letstrack.app.domain.repository.BudgetRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject

class BudgetRepositoryImpl @Inject constructor(
    private val budgetDao: BudgetDao
) : BudgetRepository {

    override fun getAllBudgets(): Flow<List<Budget>> {
        return budgetDao.getAllBudgets().map { entities -> entities.map { it.toDomainModel() } }
    }

    // "Set" always resolves to one row per categoryId (including the null/overall one) -- fetch
    // whatever row is already there first and reuse its id, otherwise REPLACE would insert a
    // second row with a new autogenerated id instead of updating the existing budget.
    override suspend fun setOverallBudget(amount: Double) {
        val existing = budgetDao.getOverallBudget()
        budgetDao.upsertBudget(BudgetEntity(id = existing?.id ?: 0, categoryId = null, amount = amount))
    }

    override suspend fun setCategoryBudget(categoryId: Long, amount: Double) {
        val existing = budgetDao.getBudgetForCategory(categoryId)
        budgetDao.upsertBudget(BudgetEntity(id = existing?.id ?: 0, categoryId = categoryId, amount = amount))
    }

    override suspend fun clearOverallBudget() {
        budgetDao.deleteOverallBudget()
    }

    override suspend fun clearCategoryBudget(categoryId: Long) {
        budgetDao.deleteBudgetForCategory(categoryId)
    }

    private fun BudgetEntity.toDomainModel() = Budget(id = id, categoryId = categoryId, amount = amount)
}
